### ISSUE TITLE
Memlet tooltip causes CPU spin with collapsed maps

### ISSUE THREAD

**Issue by sancierra** [spcl/dace-webclient#2]
Prior to the recent hotfixes, some memlet tooltips near multi-level maps were not displayed but instead the CPU would spin 100% without the tooltip ever showing. This has been fixed, however, if those maps are collapsed, the same error occurs for memlets entering and exiting that map. 
Tested on Chrome / Firefox / Safari on e7ba3f

**Comment by tbennun** [comment]
Fixed in a9176ef, please verify.
